### ISSUE TITLE
Scripting

### ISSUE THREAD

**Issue by erherhh4herh** [PanosK92/Directus3D#2]
This has some promising features already, and seems to be going in an interesting direction. But my main concern pertains to the scripting within the engine. Are there any other languages supported than C++? If not, do you plan to support other languages? Please and thank you for any answers!

**Comment by PanosK92** [comment]
Thank you,

The engine doesn't currently support any other scripting language other than the C/C++ like scripting provided by AngelScript. I have been thinking of adding Lua or C# scripting but unfortunately I can't tell you when this will happen as the engine is still in early development, and there are already a lot of things that need to be done.

Let's say though that when the engine reaches a stage where it can be considered "complete/mature", and it becomes apparent that it can be used to make games, I will definitely add support for a high level scripting language.

**Comment by Scellow** [comment]
+1 for C#, it seems to be the goto language for scripting

**Comment by erherhh4herh** [comment]
I would also plus a unity-like API (much like the unity-like editor)

**Comment by PanosK92** [comment]
I like it as well, I've just added C# scripting in the roadmap. I'll close this issue now ;-)

Regarding the editor and the API, there are no strict goals (e.g. only do what Unity does), the idea is to let it play out and see what works best. Everything is subject to change, so some things might end up being similar to other engines, other things might not be. However, everything will be intuitive and easy to use, I can assure you of that.

**Comment by JSandusky** [comment]
I could port over some Angelscript debugging via WebSockets using the asPEEK protocol. It would smooth out the experience of using Angelscript a lot. It's a really great language to use when you can debug.

I think with a few tweaks I could port over an Angelscript IDE of mine  (with intellisense and all) to include support for the Directus API and toss that up ... though being WPF based it's Windows only.
