### ISSUE TITLE
Building the editor?

### ISSUE THREAD

**Issue by erherhh4herh** [PanosK92/Directus3D#3]
Sorry if this is an ignorant question. How do I build the editor? I see the folder, but in the VS project generation it only builds a solution for the runtime. I am asking this cause I was unable to figure it out and wanted to clear things up for others who may have the same issue as I.

**Comment by PanosK92** [comment]
Thanks for letting me know,

It's not an ignorant question, it's indeed not clear how to build the editor as I wasn't expecting people to discover the engine just yet :-)

After I leave from work I'll make a proper tutorial on how to do it, it's about time I believe.

**Comment by PanosK92** [comment]
You can find a guide on how to compile from source at "https://github.com/PanosK92/Directus3D/blob/master/Documentation/CompilingFromSource/CompilingFromSource.md" or by simply clicking on the link in the README.md.

Please let me know if this was helpful in getting you to compile and run the engine.

**Comment by erherhh4herh** [comment]
Thank you for that helpful guide!! You may want to add this to the runtime building phase to ensure people's SDK isn't incorrect: https://i.imgur.com/E0eAR76.png

For whatever reason, mine was set to 8.1, which obviously cause errors.

**Comment by PanosK92** [comment]
No worries. Ah yeah, will do.

Keep in mind that the engine hasn't even reached v0.3, it's not even an alpha version and there are still a lot more things that need to be done, so keep your expectations low for the time being. 

I am closing this issue, thanks for helping out mate ;-)
