### ISSUE TITLE
Possible PhysX?

### ISSUE THREAD

**Issue by erherhh4herh** [PanosK92/Directus3D#4]
Since this engine is in it's infancy, I thought it might be a good time to question the reasoning behind the use of bullet, considering the performance degradation (although minuet with recent updates). Getting gameworks access is far from complicated, as even I got access... Please don't take this as a suggestion, it is more of a question!

EDIT:
Licensing is another thing... Although I'm pretty sure that if you made a system like the Unreal Engine has (have a bat file that grabs all needed dependencies from the respective company sites themselves), you could maintain the MIT license? I'm not sure... I ain't a lawyer :D

**Comment by PanosK92** [comment]
It's true that PhysX performs a bit better in some cases, however the performance difference can be ignored. For example, RAGE engine which was used to build GTA IV & V, is actually using Bullet. Even NASA used Bullet for a robotics project. 

So it's fair to say that when a physics library passes a certain performance threshold, it's good for most of the things you might want to do. Taking performance out of the equation, Bullet is open source and it also uses the very permissive zlib license (unlike PhysX) while providing you with everything you need.

If things change, I'll make the switch to any solution that's the best, and this goes for any part of the engine, but PhysX (for the time being) won't change your experience in a meaningful way.

If I am missing something, don't hesitate to let me know. 
Thanks for your interest erherhh4herh :-)

**Comment by erherhh4herh** [comment]
That answered my question. Thank you!

**Comment by PanosK92** [comment]
Anytime man
