### ISSUE TITLE
Link error on compiling

### ISSUE THREAD

**Issue by dragonCASTjosh** [PanosK92/Directus3D#5]
I have just pulled the latest and attempted to compile although i ended up with a link error. i followed all the instructions on the compile page

`assimp.lib(IFCUtil.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8`

**Comment by PanosK92** [comment]
Hello,

Hard to tell why it throws this linking error. It compiles fine for most people so the problem should be localized. The pre-compiled library was built with VS17 using Update 3 if I recall correctly, so this is a potential cause taking into account that in one of the next versions they did some std related changes.

In any case, I'll recompile and commit a fresh Assimp library tomorrow (I'll comment here). 
In the meantime, you might have some luck trying to download and compile Assimp yourself.

**Comment by PanosK92** [comment]
You can grab latest now, you'll get an assimp library built with the latest version of VS. 
If the problem persists, it's localized. Please keep me updated ;-)

FYI: Ideally the generated solution should include all dependencies as projects so they get compiled on the spot. This feature is not a first class citizent but I'll try to make it happen in the following months.

**Comment by dragonCASTjosh** [comment]
that seams to have fixed everything, thanks.

**Comment by PanosK92** [comment]
No problem. Just a quick reminder though, the engine is still at early development stage (plus the editor is being written from scratch again), don't expect anything fancy yet.
