### ISSUE TITLE
Possible bug report.

### ISSUE THREAD

**Issue by ianpas** [PanosK92/Directus3D#8]
In D3D11Shader.cpp file, when we use Reflect to get input layout descriptions, I found that there are two possible bugs.
![image](https://user-images.githubusercontent.com/19709093/37263411-06fb5858-25e3-11e8-8a59-6c9e4c9abad5.png)

1. when copying paramDesc.SemanticName to elementDesc.SemanticName, actually we are dealing with copying pointer (LPCSTR), instead of string. Thus after we release reflector(ID3D11ShaderReflection*), the semanticName may change.

see:
![image](https://user-images.githubusercontent.com/19709093/37263564-a97649b2-25e3-11e8-825e-1769524be73d.png)

I take a workaround to solve it:
![image](https://user-images.githubusercontent.com/19709093/37263604-de2f4352-25e3-11e8-8edc-fd022e4a6784.png)

2. elementDesc.AlignedByteOffset is not assigned correctly because D3D11_APPEND_ALIGNED_ELEMENT is a constant. However, It seems that we have to calculate it by hand: use a variable called such as offset to record the AlignedByteOffset:

![image](https://user-images.githubusercontent.com/19709093/37263697-423c6f32-25e4-11e8-8260-e608f8d40077.png)

**Comment by PanosK92** [comment]
Spot on, feel free to do a pull request if you want.
Thanks for taking the time to have a look at the code and spot these issues ianpas!

**Comment by ianpas** [comment]
You are welcome!
I'm going to do a pull request.

**Comment by PanosK92** [comment]
All good! I am closing this now ;-)
